name: CI
on: [push]
jobs:
  test-game-logic:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - run: echo "Checking out ${{ github.ref }} from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0+sha512.cf9998222162dd85864d0a8102e7892e7ba4ceadebbf5a31f9c2fce48dfce317a9c53b9f6464d1ef9042cba2e02ae02a9f7c143a2b438cd93c91840f0192b9dd
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run test
        run: pnpm run test-ci
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: ./results/unit-test-results.xml
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out ${{ github.ref }} from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0+sha512.cf9998222162dd85864d0a8102e7892e7ba4ceadebbf5a31f9c2fce48dfce317a9c53b9f6464d1ef9042cba2e02ae02a9f7c143a2b438cd93c91840f0192b9dd
      - name: Install mkcert
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-tools
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
      - name: Generate self-signed certificate
        run: |
          mkdir ssl
          mkcert -install
          mkcert --cert-file ssl/local.pem --key-file ssl/local-key.pem localhost 127.0.0.1 ::1
      - name: Have Cypress trust the CA cert generated by mkcert
        run: echo NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem" >> $GITHUB_ENV
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          start: pnpm run devs -- -L
          wait-on: 'https://localhost:5501'
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: ./results/cypress-test-results-*.xml
  publish-test-results:
    if: always()
    needs: [test-game-logic, cypress-run]
    runs-on: ubuntu-latest
    steps:
      - name: Download test results artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./results
          pattern: "*-test-results"
          merge-multiple: true
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            ./results/*-test-results*.xml
